### ISSUE TITLE
Switch from PIL to pillow

### ISSUE THREAD

**Issue by saadfarooq** [twaddington/android-asset-resizer#17]
PIL is ridiculously hard to install on some platforms (large number of Stackoverflow questions to address this but no reliable cross-platform solution). 

`pillow` seems to be the recommended package for installation via `pip`. Is it possible to convert to `pillow` without too much work ?

**Comment by aat-antoine** [comment]
Honestly, it is not really easy to install PIL whereas pillow is just a breeze. Then, you have to use @atlithorn  's solution. Thank you for that :)

**Comment by twaddington** [comment]
Instead of modifying the `setup.py` file's dependencies and maintaining a fork it's much easier to use the pip `--no-deps` command like so:

```shell
$ pip install --no-deps android-asset-resizer
$ pip install pillow
```

This will prevent the script from installing the PIL dependency and you can install pillow separately. Everything should work fine like this though I haven't done much testing with pillow.
